In [1]:
import numpy as np
import os
import sys
import pickle


In [2]:
import gzip, bz2, lzma, joblib
import traceback

path = "/Users/kiki/school/whole/results/1021_2/test_results_dict.pkl"
# path = "/Users/kiki/school/whole/results/1021_2/train_results_dict.pkl"
# path = "/Users/kiki/school/whole/results/1021_2/overall_summary.pkl"
results_dict = pickle.load(open(path, "rb"))
# with open(path, "rb") as f:
#     header = f.read(6)
#     results_dict = pickle.load(open(path, "rb"))
#     print("Loaded with pickle")

In [3]:
fid_list = results_dict.keys()
print(fid_list)
print(len(fid_list))

dict_keys([9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 48, 49, 50, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133])
115


In [7]:
results_dict['train']

{'confusion_matrix': array([[884939,    507],
        [  1663, 604667]]),
 'metrics': {'accuracy': 0.9985453580162169,
  'precision': 0.9991622244181012,
  'recall': 0.9972572691438656,
  'f1': 0.9982088379402791}}

In [8]:
results_dict['test']


{'confusion_matrix': array([[9402697,    8991],
        [   9559,  242079]]),
 'metrics': {'accuracy': 0.9980803710854834,
  'precision': 0.9641892699247222,
  'recall': 0.9620128915346648,
  'f1': 0.963099851205869}}

In [5]:
results_dict[9].keys()

dict_keys(['predictions', 'labels', 'probabilities', 'confusion_matrix', 'metrics'])

In [34]:
for key in fid_list:
    print("flight ID:", key)
    print("混淆矩阵:")
    print(results_dict[key]["confusion_matrix"])
    print("accuracy:",format(results_dict[key]["metrics"]['accuracy'], '.4f'))
    print("precision:",format(results_dict[key]["metrics"]['precision'], '.4f'))
    print("recall:",format(results_dict[key]["metrics"]['recall'], '.4f'))
    print("f1:",format(results_dict[key]["metrics"]['f1'], '.4f'))
    print("=====================================")

flight ID: 9
混淆矩阵:
[[34688     0]
 [    0 44480]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 10
混淆矩阵:
[[12284    14]
 [    0 17974]]
accuracy: 0.9995
precision: 0.9992
recall: 1.0000
f1: 0.9996
flight ID: 11
混淆矩阵:
[[    0     0]
 [ 1250 48542]]
accuracy: 0.9749
precision: 1.0000
recall: 0.9749
f1: 0.9873
flight ID: 12
混淆矩阵:
[[  471     0]
 [    0 45801]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 13
混淆矩阵:
[[68416]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 14
混淆矩阵:
[[103032      0]
 [     2      6]]
accuracy: 1.0000
precision: 1.0000
recall: 0.7500
f1: 0.8571
flight ID: 15
混淆矩阵:
[[71760     5]
 [    4     7]]
accuracy: 0.9999
precision: 0.5833
recall: 0.6364
f1: 0.6087
flight ID: 16
混淆矩阵:
[[56443   810]
 [ 7789  5422]]
accuracy: 0.8780
precision: 0.8700
recall: 0.4104
f1: 0.5577
flight ID: 17
混淆矩阵:
[[43272   168]
 [    0   976]]
accuracy: 0.9962
precision: 0.8531
recall: 1.0000
f1: 0.9208
flight ID:

In [30]:
for key in [1, 2, 3, 4, 5, 6, 7, 8, 29, 30, 32, 40, 46, 47, 51, 62, 79, 92]:
# 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 31, 33, 34, 35, 36, 37, 38, 39, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133
    print("flight ID:", key)
    print("混淆矩阵:")
    print(results_dict[key]["confusion_matrix"])
    print("accuracy:",format(results_dict[key]["metrics"]['accuracy'], '.4f'))
    print("precision:",format(results_dict[key]["metrics"]['precision'], '.4f'))
    print("recall:",format(results_dict[key]["metrics"]['recall'], '.4f'))
    print("f1:",format(results_dict[key]["metrics"]['f1'], '.4f'))
    print("=====================================")

flight ID: 1
混淆矩阵:
[[61999     2]
 [    0 34703]]
accuracy: 1.0000
precision: 0.9999
recall: 1.0000
f1: 1.0000
flight ID: 2
混淆矩阵:
[[    0     0]
 [  786 69614]]
accuracy: 0.9888
precision: 1.0000
recall: 0.9888
f1: 0.9944
flight ID: 3
混淆矩阵:
[[    0     0]
 [  284 81956]]
accuracy: 0.9965
precision: 1.0000
recall: 0.9965
f1: 0.9983
flight ID: 4
混淆矩阵:
[[    0     0]
 [  593 63631]]
accuracy: 0.9908
precision: 1.0000
recall: 0.9908
f1: 0.9954
flight ID: 5
混淆矩阵:
[[113248]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 6
混淆矩阵:
[[98976]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 7
混淆矩阵:
[[87264]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 8
混淆矩阵:
[[55264]]
accuracy: 1.0000
precision: 1.0000
recall: 1.0000
f1: 1.0000
flight ID: 29
混淆矩阵:
[[68933    27]
 [    0     0]]
accuracy: 0.9996
precision: 0.0000
recall: 0.0000
f1: 0.0000
flight ID: 30
混淆矩阵:
[[62560]]
accuracy: 1.0000
precision: 0.0000
recall: 0.0000
f1:

In [12]:
for key in results_dict.keys():
    print("flight ID:", key)
    print("混淆矩阵:")
    print(results_dict[key]["confusion_matrix"])
    print("=====================================")

flight ID: 9
混淆矩阵:
[[34679     9]
 [   36 44444]]
flight ID: 11
混淆矩阵:
[[    0     0]
 [ 1613 48179]]
flight ID: 34
混淆矩阵:
[[148288]]
flight ID: 35
混淆矩阵:
[[107648]]
flight ID: 36
混淆矩阵:
[[137954     30]
 [     0      0]]
flight ID: 98
混淆矩阵:
[[94464]]
flight ID: 99
混淆矩阵:
[[73983     0]
 [    1     0]]
flight ID: 100
混淆矩阵:
[[38012     0]
 [    4     0]]
flight ID: 101
混淆矩阵:
[[68506     0]
 [    6     0]]
flight ID: 102
混淆矩阵:
[[179264]]
flight ID: 103
混淆矩阵:
[[86398     0]
 [    2     0]]
flight ID: 104
混淆矩阵:
[[58397     0]
 [    3     0]]
flight ID: 105
混淆矩阵:
[[52123     0]
 [    5     0]]
flight ID: 106
混淆矩阵:
[[123193      5]
 [     2      0]]
flight ID: 107
混淆矩阵:
[[80918    10]
 [    0     0]]
flight ID: 108
混淆矩阵:
[[120448]]
flight ID: 109
混淆矩阵:
[[97952]]
flight ID: 110
混淆矩阵:
[[65884     1]
 [    3     0]]
flight ID: 111
混淆矩阵:
[[120150      2]
 [     8      0]]
flight ID: 112
混淆矩阵:
[[77307     0]
 [    5     0]]
flight ID: 1
混淆矩阵:
[[61993     8]
 [    3 34700]]
flight ID: 2
混淆矩阵:
[[    0  